apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-webhook
  namespace: tekton-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubectl-commands
  namespace: tekton-webhook
rules:
  - apiGroups: [""]
    resources: ["deployments"]
    verbs: ["get", "list"]
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns"]
    verbs: ["create", "get"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["create", "patch", "get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubectl-commands-binding
  namespace: tekton-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubectl-commands
subjects:
  - kind: ServiceAccount
    name: tekton-webhook
    namespace: tekton-webhook
